### ISSUE TITLE
Falta una template en la app users

### ISSUE THREAD

**Issue by lfortiz** [albertorc87/simple_blog#8]
Hola Alberto, buenas tardes me llamo Luis y te creo este issue, porque estoy siguiendo tu curso "Aprender django desde 0" y he llegado hasta el final, y he encontrado que falta la template de users de logout.html, simplemente para que la añadas.  Yo voy a intentar recrearla, aunque sólo sea para decir adiós, gracias por tu trabajo y recibe un saludo cordial

**Comment by albertorc87** [comment]
¡Hola! Al utilizar el mixin LogoutView Django automáticamente te redirecciona a la página de home cuando haces el logout, si quieres customizarlo puedes mirar a ver si te sirve esto https://stackoverflow.com/questions/59692899/using-loginview-and-logoutview-with-custom-templates
